name: Build and Package iOS App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Bazel
        run: |
          curl -LO "https://github.com/bazelbuild/bazel/releases/download/4.1.0/bazel-4.1.0-installer-darwin-x86_64.sh"
          chmod +x bazel-4.1.0-installer-darwin-x86_64.sh
          sudo ./bazel-4.1.0-installer-darwin-x86_64.sh

      - name: Build and Package
        run: |
          bazel build //project/android/jni/src:SDL_android_main --apple_generate_dsym --apple_generate_ipa --workspace=.idea/WORKSPACE.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kiriii2
          path: kiriii2.ipa
